object Versions {
    const val gson = "2.8.7"
    const val kotlin = "1.9.0"
    const val retrofit = "2.11.0"
    const val kotlin_serializer = "1.7.0-RC"
    const val hilt = "2.48"
    const val room = "2.6.1"
    const val life_cycle = "2.8.0"
    const val paging = "3.3.0"
    const val okhttp = "4.9.0"
    const val coroutines = "1.4.2"
    const val glide = "4.12.0"
    const val mockk = "1.12.0"
    const val kotlin_testing = "1.6.0"
    const val paging_testing = "3.1.0"
}